### ISSUE TITLE
Application Multiple Pages Broken

### ISSUE THREAD

**Issue by wilzdezign** [ClanTools/Tracker#11]
Looking at list of Applications /applications?withdrawn=false (to show Closed applications too)

If I click Page 2 /applications?closed=false&page=2&withdrawn=false
OR
Click Sort by Last Updated /applications?closed=false&sort=updated_at+desc&withdrawn=false

It clears the result of Applications and no longer keeps the session/page of results

**Comment by JoshuaEN** [comment]
Thank you for the report. The Closed and Withdrawn filters should now behave as expected.
