### ISSUE TITLE
Certain Replays cannot be uploaded.

### ISSUE THREAD

**Issue by meem1029** [ClanTools/Tracker#12]
This is the first time I've gotten the error, but clanmates have reported it several times. The error screen looks like ![img](http://i.imgur.com/8RIs3Bw.png). 

[Here](http://wotreplays.com/site/2128595?secret=5f70e837211ee110b217fd14d0dbe566) is the replay that I tried uploading in that specific case.

The text of the error message is "Failed to save replay data: Validation failed: Players gold is not a number"

**Comment by JoshuaEN** [comment]
Thank you for your detailed report. I'm able to duplicate the issue and am working on a fix. Will update when resolved.

**Comment by JoshuaEN** [comment]
Fixed. WG removed the "gold" field from replays in 9.10 it seems. Sorry for the trouble.
