### ISSUE TITLE
Miscount in clan lookup

### ISSUE THREAD

**Issue by joshua-michel** [ClanTools/Tracker#15]
When this message pops up: "Clan has 1 members who don't exist according to (parts of) the Wargaming.net API; statistics for these members are not available." the table of players has a miscount of the number of players. The number of players listed is correct, but the count above the table is less than the number of rows. For example: the clan [RDDT7](https://clantools.us/servers/na/clans?id=1000006758) has 62 players numbered in the table, but the count above the table says 61.

**Comment by JoshuaEN** [comment]
Hello, thank you for the bug report. I've located and fixed the issue locally; I'll be deploying the fix in a few days along with some other changes.

**Comment by JoshuaEN** [comment]
The fix now present on the live site.
