### ISSUE TITLE
clan battles played not showing up for today

### ISSUE THREAD

**Issue by Loryn-Harm** [ClanTools/Tracker#17]
Is there a problem with battles being recorded?  We played the battles, but can't upload the replays, as the battles are not showing up for today.

![harmbattles](https://cloud.githubusercontent.com/assets/19920705/16029931/ce89c356-31a1-11e6-8115-2fe8f429dd9f.JPG)

**Comment by JoshuaEN** [comment]
Hello,

The battle loader froze. I've restarted it, but any battles that ended before I did so won't be detected. Sorry for the inconvenience.
