### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by nanners35** [ClanTools/Tracker#18]
Identifier: 58c7c18d49bd5f14092b6f256c91675956b2802b | Signature: 7e07689e342a54146fc33dda148bd100e6be9aa1

**Comment by JoshuaEN** [comment]
Fixed, thanks for the report and sorry for the trouble. WG's API decided to return nothing for the English Localization of the "112_eiffel_tower_ctf" Map, which led to all of the map pickers breaking.

**Comment by nanners35** [comment]
Thank you
