### ISSUE TITLE
New Tank KV-2 (R) is missing

### ISSUE THREAD

**Issue by joshua-michel** [ClanTools/Tracker#26]
One of the newest tanks to the game, the KV-2 (R) is missing and the message says to contact the administrator. I am guessing it needs to loaded into your DB?

**Comment by JoshuaEN** [comment]
Hello,

Thank you for letting me know. Yes, I have to manually add new tanks: The KV-2 (R) has been added and should show up now (you'll have to reload the page if you already have it open).
