### ISSUE TITLE
Reward Tank distribution has been increased to 9000 licenses

### ISSUE THREAD

**Issue by Sovereignty89** [ClanTools/Tracker#27]
Reward Tank distribution has been increased to 9000 licenses. Because of server issues encountered on the 3rd of June. 

https://worldoftanks.eu/en/news/clan-wars/global-map-arms-race-start/

"The total pool of reward tanks has been increased by 500 tanks as part of a compensation for technical issues encountered on 3 June."

Could this be reflected on the website?

Thank you.

**Comment by JoshuaEN** [comment]
Hello,

It should be fixed now (you'll have to reload the page for changes to take effect). Thanks for letting me know.

**Comment by Sovereignty89** [comment]
Fast and friendly! I forgot to mention it was for EU. Thank you Joshua!
