### ISSUE TITLE
WG API Error: Unknown error related to input field application_id

### ISSUE THREAD

**Issue by synopss** [ClanTools/Tracker#28]
The title tells all :)

Is WG reworking its API ?

**Comment by JoshuaEN** [comment]
Partly; WG recently required developers to agree to the new EULA for their API, and (though I didn't think it was the case) Clan Tools was using a very old system of authenticating with the API, which doesn't work after WG began enforcing needing to agree to the EULA (which I guess they started doing today).

It should be fixed now; you'll have to reload the page for it to take effect. If you're still running into issues, please provide a link to the specific page you're encountering the error on.

Thanks!
