### ISSUE TITLE
CW webhook certification expired

### ISSUE THREAD

**Issue by joshua-michel** [ClanTools/Tracker#31]
When I manually attempt to get CW details for a clan I get an certification expiration error. Python code returns similar: `SSL: CERTIFICATE_VERIFY_FAILED`. 
In Firefox:
![ClantoolsCert](https://user-images.githubusercontent.com/3759870/55512909-58d1aa80-5632-11e9-873b-c3f683040848.PNG)

**Comment by JoshuaEN** [comment]
This should be fixed now. Thanks!
