### ISSUE TITLE
Code Type N/A

### ISSUE THREAD

**Issue by RichardKBR** [ClanTools/Tracker#34]
Codes was lost in attendance codes before 2021/04/01. 
Lost for all players.
I don't  know if someone "delete" de code type. I guess not.
Can you verify?? 
Log doesn't show this "delete"

Can you fix all N/A codes for "clan wars" type?

![image](https://user-images.githubusercontent.com/12806346/114108529-a29c9d80-98a9-11eb-8a06-b89bed47fda4.png)

**Comment by RichardKBR** [comment]
how i can pay that battles?

**Comment by RichardKBR** [comment]
Sorry, works witrh N/A anyway. All good! Can close.... or mark as resolved.

**Comment by joshua-michel** [comment]
(not developer) AFAIK the specific names of codes are deleted after some time so to not bloat the database. The codes submissions are kept with the associated code type info (Clan Wars for those you marked) for payouts and activity purposes.

**Comment by RichardKBR** [comment]
> (not developer) AFAIK the specific names of codes are deleted after some time so to not bloat the database. The codes submissions are kept with the associated code type info (Clan Wars for those you marked) for payouts and activity purposes.

Yeah.... i was terrified when i saw all listed codes was "Not Available"!
Great Tool! I make a "test payout" and worked as intended.
Thanks for tool! Can close issue.
