### ISSUE TITLE
Map ID Mismatch

### ISSUE THREAD

**Issue by dborg291** [ClanTools/Tracker#36]
`Link Error: Replay's map ID of Ghost Town (95_lost_city_ctf) didn't match Battle's map of Ghost Town (95_lost_city)`

5/14/2021
Clan War match played on Ghost Town
replay file name: ussr-R157_Object_279R_95_lost_city_ctf.wotreplay

I can confirm that the replay trying to be uploaded is the correct map and match.

**Comment by JoshuaEN** [comment]
Hi, thanks for reporting this. This should be fixed now for all existing and future battles. Please let me know if it still doesn't work.
